# docker-compose.yml
version: '3'
services:
  app1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000

  app2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
